### ISSUE TITLE
DBD-DB2 won't install from CPAN with DBI installed in local::lib

### ISSUE THREAD

**Issue by jhampson-dbre** [ibmdb/perl_DBD-DB2#1]
Hello,

There is a long standing issue with installing DBD-DB2 1.85 from cpan when using using locallib. A patch was submitted to fix it, but it has sat unmerged for some years. I have manually applied this patch and have been using it to install DBD-DB2 on our systems for a while now. Just wondering if there is a possibility of this ever being fixed upstream.

https://rt.cpan.org/Public/Bug/Display.html?id=101659

Thanks!

**Comment by AWADHAMBIKA** [comment]
Hi! @jhampson-dbre sorry for this.
We have checked in the latest code for Perl driver and are planning to manage herewith.
Can I request you to please raise a pull request here in this repo with your changes?
We will validate and merge the same.

Also, the code change mentioned in "https://rt.cpan.org/Public/Bug/Display.html?id=101659" was with respect to some GIT repo or it was done in your local system using the code from CPAN?

Thanks again for your input.

**Comment by jhampson-dbre** [comment]
There is a .patch file attached to the cpan bug. We have applied that patch to our local system on top of the code from CPAN. I will open a pull request with the fixed code for your review. Thanks for taking the time to respond!

**Comment by jhampson-dbre** [comment]
Pull request #6 is open to resolve this issue

**Comment by AWADHAMBIKA** [comment]
HI @jhampson-dbre,
I have made the changes and have uploaded the new module version i.e. 1.89 in CPAN.
Can you validate if the same is working as expected?

**Comment by jhampson-dbre** [comment]
Looks like it is working good with locallib in 1.89. Thanks for your help!

**Comment by AWADHAMBIKA** [comment]
Thanks to you @jhampson-dbre for your help. 
Really appreciate
