### ISSUE TITLE
Trying to find an IBM contact for DBD-DB2

### ISSUE THREAD

**Issue by neilb** [ibmdb/perl_DBD-DB2#2]
I'm one of the PAUSE admins. I'm trying to find someone in IBM who can confirm that the rights to this package have been transferred to Rocket Software, and so we're ok to give them permission to release new versions to CPAN?

**Comment by bimalkjha** [comment]
@ibmdb/cad-isl-php @mariobriggs Please respond. Thanks. @shilumathai FYI.
